version: '3.8'

services:
  training-postgresql-db:
    container_name: training-postgresql-db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_DATA_USER}
      POSTGRES_PASSWORD: ${DB_DATA_PASSWORD}
      POSTGRES_DB: ${DB_DATA_DATABASE}
      TZ: ${TZ}
    volumes:
      - ./db-files:/var/lib/postgresql/data
    ports:
      - ${DB_DATA_PORT}:5432
    networks:
      - training-postgresql

  training-postgresql-pgadmin:
    container_name: training-postgresql-pgadmin
    restart: always
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - training-postgresql-db
    ports:
      - ${PG_ADMIN_PORT}:80
    networks:
      - training-postgresql

networks:
  training-postgresql:
    name: training-postgresql
